# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cheerfulfly
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: file-system-api
service: file-api-service

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: dev
  environment:
    REGION: ${env:REGION}
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    APP_ENV: ${env:APP_ENV}
    AWS_BUCKET_NAME: ${env:AWS_BUCKET_NAME}
    ENCRYPTION_KEY: ${env:ENCRYPTION_KEY}

functions:
  app:
    handler: handler.handler
    events:
      - httpApi: '*'
        authorizer:
            name: cognitoAuthorizer

# Define the Cognito Authorizer for HTTP API
resources:
  Resources:
    HttpApi:
      Type: AWS::ApiGatewayV2::Api
      Properties:
        Name: ${self:service}-${self:provider.stage}
        ProtocolType: HTTP

    CognitoAuthorizer:
      Type: AWS::ApiGatewayV2::Authorizer
      Properties:
        ApiId:
          Ref: HttpApi
        AuthorizerType: JWT
        IdentitySource:
          - "$request.header.Authorization"
        Name: cognitoAuthorizer
        JwtConfiguration:
          Audience:
            - ${env:COGNITO_APP_CLIENT_ID}
          Issuer: https://cognito-idp.${self:provider.region}.amazonaws.com/${env:COGNITO_USER_POOL_ID}

plugins:
  - serverless-offline

package:
  exclude:
    - .gitignore
    - README.md
    - .env
