app: audio-recognition-api
service: audio-recognition-service


useDotenv: true


provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: dev

  httpApi:
    cors: true
    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${env:COGNITO_USER_POOL_ID}
        audience:
          - ${env:COGNITO_APP_CLIENT_ID}

  environment:
    REGION: ${env:REGION}
    APP_ENV: ${env:APP_ENV}
    ACR_CLOUD_ACCESS_KEY: ${env:ACR_CLOUD_ACCESS_KEY}
    ACR_CLOUD_SECRET_KEY: ${env:ACR_CLOUD_SECRET_KEY}

functions:
  identifyAudio:
    handler: handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
          authorizer: cognitoAuthorizer

package:
  individually: true
  patterns:
    - '!uploads/**'
    - '!node_modules/aws-sdk/**'
    - '!node_modules/ffmpeg-static/**'
    - '!node_modules/@ffprobe-installer/**'
  exclude:
    - .gitignore
    - README.md
    - .env

plugins:
  # - serverless-offline
  # - serverless-dotenv-plugin
