app: audio-recognition-api
service: audio-recognition-service


useDotenv: true


provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2
  stage: dev

  httpApi:
    cors: true
    authorizers:
      cognitoAuthorizer:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${self:provider.region}.amazonaws.com/${env:COGNITO_USER_POOL_ID}
        audience:
          - ${env:COGNITO_APP_CLIENT_ID}

  environment:
    REGION: ${env:REGION}
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    DYNAMODB_TABLE_USERS: ${env:DYNAMODB_TABLE_USERS}
    DYNAMODB_TABLE_USERS_FOLLOWS: ${env:DYNAMODB_TABLE_USERS_FOLLOWS}
    DYNAMODB_TABLE_POSTS: ${env:DYNAMODB_TABLE_POSTS}
    DYNAMODB_TABLE_COMMENTS: ${env:DYNAMODB_TABLE_COMMENTS}
    DYNAMODB_TABLE_REACTIONS: ${env:DYNAMODB_TABLE_REACTIONS}
    DYNAMODB_TABLE_CRASH_LOGS: ${env:DYNAMODB_TABLE_CRASH_LOGS}
    DYNAMODB_TABLE_PLAYLISTS: ${env:DYNAMODB_TABLE_PLAYLISTS}
    DYNAMODB_TABLE_PLAYLIST_SAVES: ${env:DYNAMODB_TABLE_PLAYLIST_SAVES}
    DYNAMODB_TABLE_AUDIO: ${env:DYNAMODB_TABLE_AUDIO}
    DYNAMODB_TABLE_VIDEO: ${env:DYNAMODB_TABLE_VIDEO}
    DYNAMODB_TABLE_IMAGE: ${env:DYNAMODB_TABLE_IMAGE}
    APP_ENV: ${env:APP_ENV}
    AWS_BUCKET_NAME: ${env:AWS_BUCKET_NAME}
    ENCRYPTION_KEY: ${env:ENCRYPTION_KEY}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_APP_CLIENT_ID: ${env:COGNITO_APP_CLIENT_ID}
    ACR_CLOUD_ACCESS_KEY: ${env:ACR_CLOUD_ACCESS_KEY}
    ACR_CLOUD_SECRET_KEY: ${env:ACR_CLOUD_SECRET_KEY}

functions:
  identifyAudio:
    handler: handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
          authorizer: cognitoAuthorizer

package:
  individually: true
  patterns:
    - '!uploads/**'
    - '!node_modules/aws-sdk/**'
    - '!node_modules/ffmpeg-static/**'
    - '!node_modules/@ffprobe-installer/**'
  exclude:
    - .gitignore
    - README.md
    - .env

plugins:
  # - serverless-offline
  # - serverless-dotenv-plugin
