name: Deploy Audio Recognition Service

on:
  workflow_dispatch:
    inputs:
      APP_ENV:
        description: Choose the development environment for deployment
        required: true
        type: choice
        options:
          - dev
          - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x" # Matches your runtime in serverless.yml

      - name: Install dependencies (audio service)
        working-directory: ./audio-recognition-service
        run: npm ci

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Deploy Audio Service
        working-directory: ./audio-recognition-service
        run: serverless deploy
        env:
          REGION: ${{ secrets.REGION }}
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
          DYNAMODB_TABLE_USERS: ${{ secrets.DYNAMODB_TABLE_USERS }}
          DYNAMODB_TABLE_USERS_FOLLOWS: ${{ secrets.DYNAMODB_TABLE_USERS_FOLLOWS }}
          DYNAMODB_TABLE_POSTS: ${{ secrets.DYNAMODB_TABLE_POSTS }}
          DYNAMODB_TABLE_COMMENTS: ${{ secrets.DYNAMODB_TABLE_COMMENTS }}
          DYNAMODB_TABLE_REACTIONS: ${{ secrets.DYNAMODB_TABLE_REACTIONS }}
          DYNAMODB_TABLE_CRASH_LOGS: ${{ secrets.DYNAMODB_TABLE_CRASH_LOGS }}
          DYNAMODB_TABLE_PLAYLISTS: ${{ secrets.DYNAMODB_TABLE_PLAYLISTS }}
          DYNAMODB_TABLE_PLAYLIST_SAVES: ${{ secrets.DYNAMODB_TABLE_PLAYLIST_SAVES }}
          DYNAMODB_TABLE_AUDIO: ${{ secrets.DYNAMODB_TABLE_AUDIO }}
          DYNAMODB_TABLE_VIDEO: ${{ secrets.DYNAMODB_TABLE_VIDEO }}
          DYNAMODB_TABLE_IMAGE: ${{ secrets.DYNAMODB_TABLE_IMAGE }}
          APP_ENV: ${{ github.event.inputs.APP_ENV }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          COGNITO_APP_CLIENT_ID: ${{ secrets.COGNITO_APP_CLIENT_ID }}

          # ACR Cloud Configuration
          ACR_CLOUD_ACCESS_KEY: ${{ secrets.ACR_CLOUD_ACCESS_KEY }}
          ACR_CLOUD_SECRET_KEY: ${{ secrets.ACR_CLOUD_SECRET_KEY }}