name: Deploy to AWS Lambda

on:

   workflow_dispatch:
    inputs:
      APP_ENV:
        description: Choose the development environment for deployment
        required: true
        type: choice
        options:
          - dev      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Install Serverless CLI
        run: npm install -g serverless

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION }}

      - name: Deploy to Lambda
        run: serverless deploy
        env:
          REGION: ${{ secrets.REGION }}
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
          APP_ENV: ${{ github.event.inputs.APP_ENV }}
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          COGNITO_USER_POOL_ID: ${{ secrets.COGNITO_USER_POOL_ID }}
          COGNITO_APP_CLIENT_ID: ${{ secrets.COGNITO_APP_CLIENT_ID }}

    #   - name: Deploy to AWS
    #     run: sls deploy --stage ${{ github.event.inputs.APP_ENV }}
    #     env:
    #       DYNAMODB_TABLE: ${{ secrets.DYNAMODB_TABLE }}
    #       AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
    #       ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
